services:
  nodo-a:
    build: .
    environment:
      NODE_ID: nodo-a
      PORT: 3000
      PEERS: http://nodo-b:3000,http://nodo-c:3000
    ports:
      - "3001:3000"
    networks:
      - mesh

  nodo-b:
    build: .
    environment:
      NODE_ID: nodo-b
      PORT: 3000
      PEERS: http://nodo-a:3000,http://nodo-c:3000
    ports:
      - "3002:3000"
    networks:
      - mesh

  nodo-c:
    build: .
    environment:
      NODE_ID: nodo-c
      PORT: 3000
      PEERS: http://nodo-a:3000,http://nodo-b:3000
    ports:
      - "3003:3000"
    networks:
      - mesh

networks:
  mesh:
    driver: bridge
